#!/usr/bin/env python3
"""Generate the standard BiomniBench task Dockerfile for tasks that lack one.

BiomniBench's HF dataset ships NO Dockerfiles — they are generated by a pipeline step
(all buildable tasks share an identical header + a data COPY). A handful of base tasks
were skipped by that step, so they (and their variants) have no `environment/Dockerfile`
and Harbor refuses to build them ("no environment definition"). Those tasks DO run
(they completed in the capability arm); they just lost the generated file.

This regenerates the faithful Dockerfile: the identical apt header every other task uses,
plus `COPY data /app/data` (equivalent to the originals' per-file COPYs — the data tree
under environment/data is reproduced verbatim at /app/data).

Usage:
  uv run python scripts/gen_default_dockerfile.py runs/harbor_tasks/da-10-1_drop_pslabels
  uv run python scripts/gen_default_dockerfile.py --force data/biomnibench-da/da-10-1
  # or many:
  uv run python scripts/gen_default_dockerfile.py runs/harbor_tasks/da-10-1_* ...
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# The header is byte-identical across all generated BiomniBench Dockerfiles (verified by
# diffing da-12-2 vs da-19-4 etc.). Only the data COPY differs, and `COPY data /app/data`
# reproduces the environment/data tree at /app/data for every task uniformly.
DOCKERFILE = """\
FROM ubuntu:24.04

# Install Python, R, and basic tools
RUN apt-get update && apt-get install -y \\
    python3 \\
    python3-pip \\
    python3-venv \\
    r-base \\
    r-base-dev \\
    curl \\
    wget \\
    git \\
    && rm -rf /var/lib/apt/lists/*

# Copy input data files into container
COPY data /app/data
WORKDIR /app
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("task_dirs", nargs="+", type=Path,
                    help="task dir(s) containing environment/data")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing Dockerfile")
    a = ap.parse_args()

    wrote = skipped = bad = 0
    for td in a.task_dirs:
        env = td / "environment"
        if not (env / "data").exists():
            print(f"SKIP {td} (no environment/data)", file=sys.stderr)
            bad += 1
            continue
        df = env / "Dockerfile"
        if df.exists() and not a.force:
            print(f"SKIP {td.name} (Dockerfile exists)")
            skipped += 1
            continue
        df.write_text(DOCKERFILE)
        print(f"WROTE {df}")
        wrote += 1
    print(f"\nwrote={wrote} skipped={skipped} bad={bad}")


if __name__ == "__main__":
    main()
